apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: default
spec:
  minReadySeconds: 45
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.network/currency-app-network: "true"
        io.kompose.service: zipkin
    spec:
      containers:
        - image: openzipkin/zipkin:latest
          imagePullPolicy: Always
          name: zipkin
          ports:
            - name: liveness-port
              containerPort: 9411
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          readinessProbe:
            httpGet:
              port: liveness-port
              path: /
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              port: liveness-port
              path: /
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    io.kompose.service: zipkin
  sessionAffinity: None

